default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: fut-std_development

test:
  <<: *default
  database: fut-std_test

production:
  <<: *default
  database: fut-std_production
  username: fut-std
  password: <%= ENV['STD_DATABASE_PASSWORD'] %>